title: 菜籽猫 CZMAO（CHINA）
description: 键盘使用说明
theme: just-the-docs

url: https://just-the-docs.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template

# 强制所有页面启用完整导航栏
defaults:
  - scope:
      path: ""          # 适用于所有页面
    values:
      nav_enabled: true # 强制显示导航栏
